#!/usr/bin/env bash
# Generates Terraform import blocks for the vargasjr.dev Cloudflare zone:
# one for the zone itself, one per DNS record. Output feeds
# `terraform plan -generate-config-out` so HCL is written for us.
#
# Usage:  ./import-records.sh [zone-name] [output-file]
# Env:    CLOUDFLARE_API_TOKEN (required) — needs Zone:Read + DNS:Read
# Deps:   curl, jq
set -euo pipefail

ZONE_NAME="${1:-vargasjr.dev}"
OUT="${2:-import.tf}"
: "${CLOUDFLARE_API_TOKEN:?export CLOUDFLARE_API_TOKEN first}"
command -v jq >/dev/null || { echo "jq is required"; exit 1; }

CF_API="https://api.cloudflare.com/client/v4"

ZONE_ID=$(curl -sfS -H "Authorization: Bearer $CLOUDFLARE_API_TOKEN" \
  "$CF_API/zones?name=$ZONE_NAME" | jq -r '.result[0].id // empty')
[[ -n "$ZONE_ID" ]] || { echo "Zone $ZONE_NAME not found — is the token scoped to it?"; exit 1; }

{
  echo "# Generated by import-records.sh — review before use."
  echo "# Delete this file after the first successful \`terraform apply\`."
  echo "import {"
  echo "  to = cloudflare_zone.this"
  echo "  id = \"$ZONE_ID\""
  echo "}"
} > "$OUT"

# One import block per DNS record. Apex NS records are Cloudflare-managed
# system records and cannot be imported, so they are skipped.
declare -A seen=()
curl -sfS -H "Authorization: Bearer $CLOUDFLARE_API_TOKEN" \
  "$CF_API/zones/$ZONE_ID/dns_records?per_page=100" \
| jq -r '.result[] | [.id, .type, .name] | @tsv' \
| while IFS=$'\t' read -r id type name; do
    [[ "$type" == "NS" && "$name" == "$ZONE_NAME" ]] && continue
    [[ "$type" == "NS" && "$name" == "$ZONE_NAME." ]] && continue

    part="${name%.$ZONE_NAME}"
    part="${part%.}"
    [[ -z "$part" ]] && part="apex"
    [[ "$part" == "$name" ]] && part="apex"

    slug="$(echo "${type,,}_${part}" | tr -c 'a-z0-9' '_' | sed -e 's/_*$//' -e 's/^$/apex/')"
    if [[ -n "${seen[$slug]:-}" ]]; then
      seen[$slug]=$(( seen[$slug] + 1 ))
      slug="${slug}_${seen[$slug]}"
    else
      seen[$slug]=1
    fi

    cat >> "$OUT" <<EOF
import {
  to = cloudflare_dns_record.$slug
  id = "$ZONE_ID/$id"
}
EOF
  done

echo "Wrote $OUT — review it, then:"
echo "  terraform plan -generate-config-out=generated.tf"
