name: ci

on:
  push:
    branches:
      - main
    paths:
      - "app/**"
      - "eslint.config.mjs"
      - "package.json"
      - "knip.json"
      - ".github/workflows/ci.yaml"
  pull_request:
    paths:
      - "app/**"
      - "eslint.config.mjs"
      - "package.json"
      - "knip.json"
      - ".github/workflows/ci.yaml"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: Install dependencies
        run: npm install --ignore-scripts
      - name: Run ESLint
        run: npx eslint app/ lib/ scripts/
      - name: Run Prettier check
        run: npx prettier --check .
